version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - simonovic86
  assignees:
  - simonovic86
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: "@ceramicnetwork/http-client"
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.9.5
    - 0.9.6
  - dependency-name: "@ceramicnetwork/docid"
    versions:
    - 0.4.5
    - 0.4.6
    - 0.5.0
    - 0.5.1
    - 0.5.2
  - dependency-name: "@ceramicnetwork/common"
    versions:
    - 0.15.8
    - 0.15.9
    - 0.16.0
    - 0.17.0
    - 0.17.1
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.10.1
    - 6.9.2
  - dependency-name: dids
    versions:
    - 1.1.1
    - 2.0.0
    - 2.0.1
    - 2.1.0
  - dependency-name: "@ceramicnetwork/3id-did-resolver"
    versions:
    - 0.6.10
    - 0.6.9
    - 1.1.0
    - 1.1.1
    - 1.1.2
  - dependency-name: ethers
    versions:
    - 5.0.26
    - 5.0.29
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.3
  - dependency-name: multiformats
    versions:
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.5.3
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 6.0.0
    - 6.0.1
  - dependency-name: aws-cron-parser
    versions:
    - 1.1.7
